    @Test
    public void testCause() {
        Exception throwable = new Exception("Placeholder");

        SAXException sax2 = new SAXException(throwable);
        assertSame(throwable, sax2.getCause());
        assertSame(throwable, sax2.getException());

        // Workaround with ServiceException
        ServiceException serviceException1 =
                (ServiceException) new ServiceException("example").initCause(throwable);
        assertSame(throwable, serviceException1.getCause());
        assertSame(throwable, serviceException1.getException());
    }

